MiniShopBundle\Entity\Product:
    type: entity
    repositoryClass: MiniShopBundle\Entity\ProductRepository
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        price:
            type: decimal
            scale: 2
        created_at:
            type: datetime
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
    oneToMany:
        photos:
            targetEntity: Photo
            mappedBy: product
            cascade: [persist]
